### ISSUE TITLE
list of lists is showing as fixed; no way to edit that type of parameters

### ISSUE THREAD

**Issue by breengles** [brentyi/tyro#101]
First of all, thanks for a great easy-to-use library!
In my some kind of weird usage  need to specify list of lists of some variable (let it be `int` for now). Here is an example:
```python
from dataclasses import dataclass, field

import tyro


@dataclass
class Config:
    a: list[list[int]] = field(default_factory=lambda: [[1], [1]])
    b: list[int] = field(default_factory=lambda: [1, 1])


print(tyro.cli(Config))
```

this yield in the following help
```bash
usage: test.py [-h] [--a {fixed}] [--b [INT [INT ...]]]

╭─ arguments ─────────────────────────────────────────────╮
│ -h, --help              show this help message and exit │
│ --a {fixed}             (fixed to: [[1], [1]])          │
│ --b [INT [INT ...]]     (default: 1 1)                  │
╰─────────────────────────────────────────────────────────╯
```

and obviously parser complains that this argument is fixed and cannot be parsed:
```bash
Error parsing --a: --a was passed in, but is a fixed argument that cannot be parsed
```

Is there any workaround or maybe plans to support such kind of data?

**Comment by brentyi** [comment]
Hi!

Yes, unfortunately annotations where we have a variable-length sequence type nested in another variable-length sequence type aren't compatible with how we convert sequence types by default. There are a few options here though:

**(1)** If the inner list has a known length, for example 3, you can also use an annotation like `list[tuple[int, int, int]]`.

**(2)** [`tyro.conf.UseAppendAction[]`](https://brentyi.github.io/tyro/api/tyro/conf/#tyro.conf.UseAppendAction) lets you append to the list.

```python
@dataclass
class Config:
    a: tyro.conf.UseAppendAction[list[list[int]]] = field(default_factory=lambda: [[1], [1]])
    b: list[int] = field(default_factory=lambda: [1, 1])

print(tyro.cli(Config))
```

```
$ python test.py --a 1 2 3 --a 4 5 6
Config(a=[[1], [1], [1, 2, 3], [4, 5, 6]], b=[1, 1])
```

**(3)**  [`tyro.conf.arg(constructor=...)`](https://brentyi.github.io/tyro/api/tyro/conf/#tyro.conf.arg) lets you hand-specify how a type is parsed. For example, we can take a JSON string from the commandline:

```python
from dataclasses import dataclass, field
from typing import Annotated

import tyro
import json

@dataclass
class Config:
    a: Annotated[list[list[int]], tyro.conf.arg(constructor=json.loads, metavar="JSON")] = field(
        default_factory=lambda: [[1], [1]]
    )
    b: list[int] = field(default_factory=lambda: [1, 1])

print(tyro.cli(Config))
```

```
python test.py --a "[[1,2],[3,4]]"
Config(a=[[1, 2], [3, 4]], b=[1, 1])
```

Let me know if any of that is unclear!

**Comment by breengles** [comment]
Thanks a lot for such a quick reply! 
This indeed seems like a solution to my use case! I will close the issue :hugs:
