### ISSUE TITLE
Overriding default values in dataclasses/Pydantic

### ISSUE THREAD

**Issue by kevinddchen** [brentyi/tyro#107]
`tyro` can override parameters of a dataclass when you give it a concrete instance:

```python
# a.py

import dataclasses

import tyro


@dataclasses.dataclass
class DataclassConfig:
    a: int = 1


def main(config_dc: DataclassConfig = DataclassConfig(a=2)) -> None:
    pass


tyro.cli(main)
```

```bash
$ python a.py -h
usage: a.py [-h] [--config-dc.a INT]

╭─ arguments ─────────────────────────────────────────────╮
│ -h, --help              show this help message and exit │
╰─────────────────────────────────────────────────────────╯
╭─ config-dc arguments ───────────────────────────────────╮
│ --config-dc.a INT       (default: 2)                    │
╰─────────────────────────────────────────────────────────╯
```

However, this doesn't work for Pydantic models:

```python
# a.py

import dataclasses

import pydantic
import tyro


@dataclasses.dataclass
class DataclassConfig:
    a: int = 1


class PydanticConfig(pydantic.BaseModel):
    a: int = 1


@pydantic.dataclasses.dataclass
class PydanticDataclassConfig:
    a: int = 1


def main(
    config_dc: DataclassConfig = DataclassConfig(a=2),
    config_py: PydanticConfig = PydanticConfig(a=2),
    config_pydc: PydanticDataclassConfig = PydanticDataclassConfig(a=2),
) -> None:
    pass


tyro.cli(main)
```

```bash
$ python a.py -h
usage: a.py [-h] [--config-dc.a INT] [--config-py.a INT] [--config-pydc.a INT]

╭─ arguments ─────────────────────────────────────────────╮
│ -h, --help              show this help message and exit │
╰─────────────────────────────────────────────────────────╯
╭─ config-dc arguments ───────────────────────────────────╮
│ --config-dc.a INT       (default: 2)                    │
╰─────────────────────────────────────────────────────────╯
╭─ config-py arguments ───────────────────────────────────╮
│ --config-py.a INT       (default: 1)                    │  # <== expect to be 2
╰─────────────────────────────────────────────────────────╯
╭─ config-pydc arguments ─────────────────────────────────╮
│ --config-pydc.a INT     (default: 2)                    │
╰─────────────────────────────────────────────────────────╯
```

Is this overriding behavior intended? If so, is it easy enough to fix for Pydantic models? I am on `pydantic==2.5.2` and `tyro==0.6.0` but I checked that I get the same behavior all the way down to `pydantic<2` and `tyro==0.5.4` (when Pydantic 2 support was added).

**Comment by kevinddchen** [comment]
More importantly: If you want this change, I don't mind diving into the muck and trying to make the contribution myself.

**Comment by brentyi** [comment]
Oof yes, this is definitely something I overlooked!

Basically this logic in `_field_list_from_pydantic()` for filling the default value of Pydantic fields: https://github.com/brentyi/tyro/blob/ed0eaacafb903a58a690b3940eb73e6fa92ae9cf/tyro/_fields.py#L633-L637
...is missing logic for incorporating the value of `default_instance` (`=PydanticConfig(a=2)` in your case). `_field_list_from_attrs()` looks incomplete in the same way.

As a reference for what should be happening, the [code for parsing fields in dataclasses](https://github.com/brentyi/tyro/blob/ed0eaacafb903a58a690b3940eb73e6fa92ae9cf/tyro/_fields.py#L557-L576) calls [`_get_dataclass_field_default()`](https://github.com/brentyi/tyro/blob/ed0eaacafb903a58a690b3940eb73e6fa92ae9cf/tyro/_fields.py#L974-L1024), which does take the value of `default_instance` into account. It seems like the logic for `_get_dataclass_field_default()` could be either duplicated or consolidated — if you have time to help fix this that'd be super appreciated!

**Comment by brentyi** [comment]
Maybe we could reimplement `_get_dataclass_field_default(field: dataclasses.Field, parent_default_instance: Any) -> Optional[Any]` as:
- `_get_dataclass_field_default(field: Union[dataclasses.Field, pydantic.Field], parent_default_instance: Any) -> Any`

or, if we have time:
- `_get_dataclass_field_default(field: Union[dataclasses.Field, pydantic.Field, attrs.Attribute], parent_default_instance: Any) -> Any`
?

(aside: it looks like the `Optional[Any]` return annotation can be safely replaced with just `Any`, it's equivalent + we never return `None` so this looks like just some vestigial quirk)

**Comment by kevinddchen** [comment]
Sure! I'll probably be slow, but at the least I can offer you entertainment as I faff about 😆

**Comment by brentyi** [comment]
I think you'll be alright but do let me know if you have questions 🙂 

Hopefully it's just a matter of translating the `dataclasses`-specific syntax to the `pydantic` equivalents. If you decide you don't have time or something I'm also happy to fix it.

**Comment by tungalbert99** [comment]
I'm excited for this fix!
