### ISSUE TITLE
disable typing options for some entier classes?

### ISSUE THREAD

**Issue by jizongFox** [brentyi/tyro#116]
Hello team, 

thank you for the wonderful work. I am wondering if I can disable the typing options for some whole classes, where they are fixed during all the process. 
![image](https://github.com/brentyi/tyro/assets/24821325/f1e49641-fd9a-4db9-99bf-ec15c0569e2e)

For example, for data.split.chunk-split ...., I dont want them to appear to the cmd and indeed we have many many chunks, which makes the parser extremely slow. 

I understand I can put Suppress[ ] as a hint but it cannot speed up the parser.  Is there an alternative way?

Best

**Comment by brentyi** [comment]
Hi!

A few quick questions:
- Are you on `0.6.4` of `tyro`? If not, could you try upgrading*?
- Do you have any numbers on how slow is slow, and how many arguments you're creating? It would be helpful to know which part of `tyro` is the bottleneck, for example, and how it compares to things like import times.
- Are you using subcommands, or just nesting dataclasses?

*As of 0.6.4, if we write:
```python
from dataclasses import dataclass

import tyro


@dataclass(frozen=True)
class Child:
    field: int


@dataclass(frozen=True)
class Config:
    child: tyro.conf.Suppress[Child] = Child(3)


tyro.cli(Config)
```
We shouldn't be populating (suppressed) arguments for `Child` anymore.
