### ISSUE TITLE
Faster + lazy helptext generation

### ISSUE THREAD

**Issue by brentyi** [brentyi/tyro#14]
`nerfstudio`'s `ns-train` function currently has ~500 arguments, which results in a nearly 0.4 (!!) second `dcargs` overhead. That's huge!

It's currently still a small part of overall startup time, but some profiling shows that most of it is spent on helptext formatting; about 0.1 seconds for `rich` operations and 0.2 seconds for docstring parsing. 

Most of the time, the helptext isn't even used; we should find ways to run less logic and faster logic. More intelligent caching and lazy strings would likely speed things up by ~an order of magnitude.

**Comment by brentyi** [comment]
latest commits add more aggressive caching + lazy string formatting => 3~4x speedup

**Comment by dexin-qi** [comment]
tyro is tooooooo slow

**Comment by brentyi** [comment]
If you want this improves some more constructive details would be nice, feel free to file a separate issue 🙂

**Comment by brentyi** [comment]
If you want this improved more constructive details would be nice, feel free to file a separate issue :)

**Comment by dexin-qi** [comment]
Sorry, I messed up the code, causing you trouble. I apologize.

**Comment by brentyi** [comment]
Haha glad you figured it out!

I am actually pretty unsatisfied with `tyro`'s performance on larger codebases; it's ok on faster CPUs, but nerfstudio currently populates 5000+ arguments each time you run the training script, which can take as long as a second if you're on an older machine. sdfstudio might be similar.

This is still small relative to the overall startup time, but feels unacceptable long-term...
