### ISSUE TITLE
Is tyro compatible with argparse?

### ISSUE THREAD

**Issue by Colezwhy** [brentyi/tyro#146]
Hi, great development tools, much thanks!
But I wonder is tyro compatible with argparse? If I want to use tyro and argparse at the same time, how should I make them both work?

**Comment by brentyi** [comment]
Hello! tyro is built on top of argparse, but is designed to completely abstract argparse away. Using the tyro API simultaneously with the under-the-hood argparse API isn't a design goal.

You could try simple-parsing (https://github.com/lebrice/SimpleParsing) or jsonargparse (https://github.com/omni-us/jsonargparse)!

**Comment by Colezwhy** [comment]
> Hello! tyro is built on top of argparse, but is designed to completely abstract argparse away. Using the tyro API simultaneously with the under-the-hood argparse API isn't a design goal.
> 
> You could try simple-parsing (https://github.com/lebrice/SimpleParsing) or jsonargparse (https://github.com/omni-us/jsonargparse)!

Got it now! Thank you.
