### ISSUE TITLE
Allow `TypedDict` to have default value, or allow `dataclass` to be “unset by default” (both via annotations)

### ISSUE THREAD

**Issue by stevapple** [brentyi/tyro#159]
In a program we may want to let the user know a config is left “unset” by default (instead of exposing the `None` value, which we regard as a kind of implementation detail). AFAIK only `TypedDict` allows this, so we end up using it instead of `dataclass`. However, unlike `dataclass`, `TypedDict` doesn’t support default value, so we can only use `default=` on `tyro.cli` to pass default value, which is pretty’s awkward (we want all default values be alongside with its definition!).

Given that `tyro` already supports annotations on `dataclass` and `TypedDict` fields, I’m wondering if we can add a `default=` in `tyro.conf.args` that’s exclusive to `tyro` (i.e. won’t be set if it’s created manually). Or alternatively, I would also appreciate if we add some annotation to allow `Optional` fields in a `dataclass` to be “unset by default”.

**Comment by stevapple** [comment]
May it be more general by allowing customization of the '(default: %(default))' description with an annotation? This should be less specialized.

**Comment by brentyi** [comment]
Makes sense; can you see if the API in #161 seems reasonable to you?

**Comment by brentyi** [comment]
Should be resolved in `tyro==0.8.11`!
