### ISSUE TITLE
Support for Enum aliases

### ISSUE THREAD

**Issue by kevinddchen** [brentyi/tyro#160]
Hello! Long time no see 🙂 . Python has pretty nice guarantees for Enum aliases,

```python
>>> class MyEnum(enum.Enum):
...     A = 1
...     B = 2
...     C = 2
...
>>> MyEnum.B is MyEnum.C
True
>>> MyEnum.__members__
mappingproxy({'A': <MyEnum.A: 1>, 'B': <MyEnum.B: 2>, 'C': <MyEnum.B: 2>})
>>> list(MyEnum)
[<MyEnum.A: 1>, <MyEnum.B: 2>]
```

Can we make `tyro` support Enum aliases? The following script currently breaks:

```python
import enum
import tyro


class MyEnum(enum.Enum):

    A = 1
    B = 2
    C = 2


def main(x: MyEnum) -> None:
    print(x)


tyro.cli(main, args=["--x", "A"])
tyro.cli(main, args=["--x", "B"])
# tyro.cli(main, args=["--x", "C"])
# ^ this errors out!
```

If so, I don't mind making the fix.

**Comment by brentyi** [comment]
Hi @kevinddchen!

Yeah, supporting this makes sense and would be appreciated. It seems like it would a one-liner here:
https://github.com/brentyi/tyro/blob/fcadb01918c4ad419ce5edd10057bfdeee5b837a/src/tyro/_instantiators.py#L280
and then tests. 🙂
