### ISSUE TITLE
Feature?: Allow conflicting option strings/names for supressed arguments

### ISSUE THREAD

**Issue by mirceamironenco** [brentyi/tyro#170]
Would it be possible to handle naming conflicts differently if the arguments are to be ignored/suppressed anyway? Example:

```py
from dataclasses import dataclass

import tyro


class LayerAExample:
    def __init__(self, **kwargs): ...


@dataclass
class LayerAConfig:
    _target: type = LayerAExample
    foo: int = 13


class LayerBExample:
    def __init__(self, **kwargs): ...


@dataclass
class LayerBConfig:
    _target: type = LayerBExample
    bar: int = 13


@dataclass
class BlockConfig:
    layer_a: LayerAConfig
    layer_b: LayerBConfig


if __name__ == "__main__":
    tyro.cli(tyro.conf.OmitArgPrefixes[tyro.conf.SuppressFixed[BlockConfig]])
```

Fails with `argparse.ArgumentError: argument --_target: conflicting option string: --_target`, due to `OmitArgPrefixes`, but the conflict occurs for suppressed arguments.

**Comment by brentyi** [comment]
Hey @mirceamironenco, sorry for the late reply! Yes, it would make sense to change the behavior for this. I'm working through a set of deadlines right now but will add to the to-do list for after.
