### ISSUE TITLE
Cannot use `tuple` and `list` in python 3.9

### ISSUE THREAD

**Issue by Msadat97** [brentyi/tyro#19]
Hi all,

I have a problem when using the new `tuple` and `list` type annotation with tyro. It gives me the following error:

```
AttributeError: type object 'tuple' has no attribute 'copy_with'
```

The code runs fine with `Tuple` and `List`.

**Comment by brentyi** [comment]
Hi! Can you make sure you're on the latest version via `pip install tyro --upgrade` and try again?

If it's still failing, could you provide an example for reproducing?

There are [unit tests](https://github.com/brentyi/tyro/blob/main/tests/test_new_style_annotations_only_py310.py) for this that seem to be passing, so I'd expect this to work.

**Comment by Msadat97** [comment]
> 
I checked again, and I have the latest version of tyro. The following code should reproduce my error:

```python
from dataclasses import dataclass
from typing import List, Tuple
import tyro

@dataclass
class Dummyconfig:
    a: int = 1
    b: tuple[int, ...] = (1, 2, 3)

args = tyro.cli(Dummyconfig)
print(args)
```

**Comment by brentyi** [comment]
Ah -- seems like we were only catching this for Python 3.10, and not 3.9. I just pushed a fix + release.

Thanks for flagging, do you mind upgrading and checking one more time?

**Comment by Msadat97** [comment]
It is fixed now. Thanks for the quick update!

**Comment by brentyi** [comment]
Great!
