### ISSUE TITLE
Pypi package ships tests but not test utilities

### ISSUE THREAD

**Issue by erooke** [brentyi/tyro#195]
The pypi package right now ships all the files matching `tests/test_*.py` but no other files in the `test` directory such as `helptext_utils`. This makes the tests in the pypi distribution basically useless, it seems that the entire `test` directory should be shipped or excluded.

**Comment by brentyi** [comment]
Thanks for pointing this out! I'll remove this from the distribution.

**Comment by brentyi** [comment]
For posterity, the reason for this behavior is setuptools: https://setuptools.pypa.io/en/latest/userguide/miscellaneous.html

In particular, it includes in the package all:

> Files that match the following glob patterns: `tests/test*.py`, `test/test*.py`;
