### ISSUE TITLE
"use_underscores" useless?!?

### ISSUE THREAD

**Issue by jedie** [brentyi/tyro#205]
I use `tyro.extras._subcommand_app.SubcommandApp()` and it seems that `use_underscores` passed to `app.cli()` doesn't change anything.

**Comment by brentyi** [comment]
To clarify, is the missing behavior you're describing:

- When `use_underscores=False`, for a function `some_subcommand()` to be converted to `some-subcommand` in the CLI?
- When `use_underscores=True`, for a function `some_subcommand()` to be converted to `some_subcommand` in the CLI?

If so I agree there's some missing functionality!

**Comment by jedie** [comment]
> When use_underscores=False, for a function some_subcommand() to be converted to some-subcommand in the CLI?

And this will be not done.

I use a ugly work-a-round: `app._subcommands = {k.replace('_', '-'): v for k, v in app._subcommands.items()}`
