### ISSUE TITLE
Running CI only against Python 3.12 ?!?

### ISSUE THREAD

**Issue by jedie** [brentyi/tyro#206]
Seems that the tests at github runs only with Python 3.12 ?

https://github.com/brentyi/tyro/blob/604992e38facb82d6b8767deea0c919a5ebbb98e/.github/workflows/coverage.yml#L17

**Comment by jedie** [comment]
I just wondering, because i get: 
```
  File "/home/jens/repos/cookiecutter_templates/.tox/3.13/lib/python3.13/site-packages/cli_base/tyro_commands.py", line 11, in <module>
    UseCounterAction[int],
    ~~~~~~~~~~~~~~~~^^^^^
  File "/home/jens/repos/cookiecutter_templates/.tox/3.13/lib/python3.13/site-packages/tyro/conf/_markers.py", line 167, in __getitem__
    return Annotated.__class_getitem__((key, self))  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jens/.local/share/uv/python/cpython-3.13.0-linux-x86_64-gnu/lib/python3.13/typing.py", line 548, in __getattr__
    raise AttributeError(item)
AttributeError: __class_getitem__
```
and checked tyro and python 3.13 compatibility... so i found that CI runs only with 3.12...
But now i also saw https://github.com/brentyi/tyro/pull/200 that fixed the `AttributeError: __class_getitem__` error...

Anyway: Think the CI test matrix should reflect the supported python versions, isn't it?

**Comment by brentyi** [comment]
That workflow is actually just the coverage one (which we only do in 3.12), but the other test one ("build") is indeed missing 3.13 in the matrix:

https://github.com/brentyi/tyro/blob/604992e38facb82d6b8767deea0c919a5ebbb98e/.github/workflows/build.yml#L14

**Comment by brentyi** [comment]
From what I've seen "build" is a standard job name for installing a package + dependencies and running tests: https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-python#running-tests-with-tox

But I do think "tests" or just "pytest" is clearer. I can rename!
