### ISSUE TITLE
if it's possible to loose `docstring-parser` to `^0.16` for conflict with `instructor`

### ISSUE THREAD

**Issue by zhuoqun-chen** [brentyi/tyro#212]
Hi @brentyi, thx for making this amazing project!

Currently,
https://github.com/instructor-ai/instructor/blob/main/pyproject.toml restricts `docstring-parser = "^0.16"`
this usually be parsed by pip to be `>=0.15, <0.16`.

However, `tyro` uses `docstring-parser>=0.16`, so I always have pip conflict when trying to install them both under the same environment.

So I wonder if this dependency in `tyro` can be loosed? If this is for some compatibility consideration, I will also make an issue to `instructor` repo.

Thx!

**Comment by zhuoqun-chen** [comment]
I downgraded `tyro` to `0.8.4` and this solves the problem.

**Comment by brentyi** [comment]
Hi @zhuoqun-chen, recent versions of tyro should work fine with 0.15 also. I'll relax this requirement in #213.
