### ISSUE TITLE
Setting docstrings for dynamic dataclasses

### ISSUE THREAD

**Issue by tovacinni** [brentyi/tyro#25]
Another weird question:

Is it possible to set docstrings programatically for dynamic dataclasses?

A quick look through the source seems to indicate that this isn't possible, since for dataclasses it relies on the source existing, and seems to default to returning None in the case it detects that the object is a dynamic dataclass.

It could be super useful if you could add optional support for docs with dynamic dataclasses, for purposes like dynamically generating schemas from class definitions / function definitions. It's not super elegant but this could be exposed through the `metadata` field of `dataclasses.field`, which according to the docs is meant for 3rd party extensions for dynamic dataclasses.

**Comment by tovacinni** [comment]
In case this is a feature that you'd be interested in supporting, I put up a PR here: https://github.com/brentyi/tyro/pull/26

**Comment by brentyi** [comment]
Thanks @tovacinni! This is a good question, probably also relevant to #23.

There should be (at least?) two existing approaches for getting helptext messages here. Curious about your thoughts on how they compare to your solution:
1. By modifying the annotated type: `tyro.conf.arg()` can be used to add helptext to any arbitrary field. ([API reference](https://brentyi.github.io/tyro/api/tyro/conf/#tyro.conf.arg), [relevant example](https://brentyi.github.io/tyro/examples/04_additional/06_conf/))
2. Something I added to support config dataclasses written for HuggingFace models is parsing a "help" field from dataclass metadata; here's the [relevant bit in the code](https://github.com/brentyi/tyro/blob/0c82e42afc5bdceee34e0fe27b57c3ee1eecb355/tyro/_fields.py#L346-L349).

(1) is the API I would encourage; it's verbose, but more general / not restricted to dataclasses and avoids the string dictionary key. Probably I should add this to the "Helptext generation" page in the documentation.

Here's a runnable example:
```python
from dataclasses import field, make_dataclass

from typing_extensions import Annotated

import tyro

DynamicDataclass = make_dataclass(
    "DynamicDataclass",
    [
        ("field", str, field()),
        # (1) Helptext via type annotation.
        (
            "field_help1",
            Annotated[str, tyro.conf.arg(help="Helptext for this field.")],
            field(),
        ),
        # (2) Helptext in the same style as expected by HuggingFace's hf_argparser.
        (
            "field_help2",
            str,
            field(metadata={"help": "HuggingFace-style helptext."}),
        ),
    ],
)

tyro.cli(DynamicDataclass)
```

**Comment by tovacinni** [comment]
Hi @brentyi, thanks so much for the super helpful pointers!! 

I didn't realize the metadata help text already existed- I think this is functionally equivalent to the `docs` metadata I put in the MR (so I don't think the MR approach has any advantages). I quickly tried it on my side and seems to work great.

I also tried the encouraged API and it also works- keeps my code a little cleaner too. :grin: Thanks for this super awesome lib!
