### ISSUE TITLE
Subcommands are broken

### ISSUE THREAD

**Issue by kevinddchen** [brentyi/tyro#29]
Given this file,
```
# tyro_test.py

from dataclasses import dataclass
from typing import Union

import tyro


@dataclass
class DataparserA:
    pass


@dataclass
class DataparserB:
    pass


Dataparser = Union[DataparserA, DataparserB]


@dataclass
class ModelA:
    pass

@dataclass
class ModelB:
    pass


Model = Union[ModelA, ModelB]


@dataclass
class Pipeline:
    dataparser: Dataparser
    model: Model


@dataclass
class Trainer:
    pipeline: Pipeline


tyro.cli(Trainer)
```
When I run with `python tyro_test.py pipeline.dataparser:dataparser-a  pipeline.model:model-a`, I get this following error with `tyro==0.3.35` and `==0.3.36`:
```
Traceback (most recent call last):
  File "/home/kchen/mttr_nerfstudio/tyro_test.py", line 43, in <module>
    tyro.cli(Trainer)
  File "/home/kchen/miniconda3/envs/nerfstudio/lib/python3.10/site-packages/tyro/_cli.py", line 125, in cli
    _cli_impl(
  File "/home/kchen/miniconda3/envs/nerfstudio/lib/python3.10/site-packages/tyro/_cli.py", line 326, in _cli_impl
    out, consumed_keywords = _calling.call_from_args(
  File "/home/kchen/miniconda3/envs/nerfstudio/lib/python3.10/site-packages/tyro/_calling.py", line 100, in call_from_args
    value, consumed_keywords_child = call_from_args(
  File "/home/kchen/miniconda3/envs/nerfstudio/lib/python3.10/site-packages/tyro/_calling.py", line 110, in call_from_args
    subparser_def = parser_definition.subparsers_from_prefix[
KeyError: 'pipeline.model'
```

- I do not get an error if I use `tyro==0.3.33`
- I do not get an error if I use `tyro==0.3.35` but change the last line to `tyro.cli(Pipeline)` and then run `python tyro_test.py dataparser:dataparser-a  model:model-a`

Maybe this is related to the new `tyro.conf.ConsolidateSubcommandArgs` functionality? But I am not sure. Sorry, for just dumping the error and not looking into the source--I don't have much time right now.

**Comment by kevinddchen** [comment]
The error also occurs on the most recent commit to main, [444fbf9](https://github.com/brentyi/tyro/commit/444fbf9629c13b218f62a0c7ab5087e0fd8da50b)

**Comment by brentyi** [comment]
Hi!

Definitely no worries on looking into the source, the internal complexity of tyro has definitely ballooned and it doesn't seem like that kind of thing would be a good use of your time. RIP my 100-line CLI generation utility. :smiling_face_with_tear: 

You reproduction instructions were really helpful, can you check if `0.3.37` fixes this issue?

**Comment by kevinddchen** [comment]
Yes! That seems to have fixed it :) Thank you!

Great job on this library. I always wanted a `dataclass -> CLI`, but was not satisfied with the existing alternatives since they don't support typing fully. I pretty much exclusively use tyro when I want a CLI now.
