### ISSUE TITLE
Handling unions with `os.PathLike`

### ISSUE THREAD

**Issue by JesseFarebro** [brentyi/tyro#36]
I'm running into an issue currently trying to parse a type like: `Union[str, os.PathLike]`. An instantiator can't be resolved for `PathLike` as it's an abstract base class. Can an exception be made specifically for `os.PathLike` as it's so commonly used. e.g., https://github.com/google/etils/blob/main/etils/epath/typing.py#L24

As of Python 3.10 `PathLike` is a generic type and can be parameterized, e.g., `PathLike[str]` so it might be possible to fold in this type on Python 3.10+. I'm not sure if there's an easy way to accomplish this in the short term besides adding another exception here: https://github.com/brentyi/tyro/blob/main/tyro/_instantiators.py#L388-L393. 

Thoughts?

**Comment by brentyi** [comment]
Thanks! I'm okay with special-casing this, does #37 looks reasonable?

**Comment by brentyi** [comment]
Also, I couldn't find any documentation on using `PathLike` as a generic, aside from the comment / error in `etils`. Do you have a reference for this?

**Comment by JesseFarebro** [comment]
@brentyi interestingly it was added with [PEP 585](https://peps.python.org/pep-0585/): https://github.com/python/cpython/blame/main/Lib/os.py#L1093

There seems to be no documentation and it's not discussed in PEP 585 so perhaps this was by mistake?
