### ISSUE TITLE
Support variadic positional and keyword arguments

### ISSUE THREAD

**Issue by JesseFarebro** [brentyi/tyro#39]
This shouldn't be too hard. Just a matter of changing the type when parsing the signature and having another internal marker to unpack the arguments before the call.

e.g.,

```py
def main(*args: str, **kwargs: str) -> Tuple[Tuple[str], Dict[str, str]]:
    return args, kwargs

tyro.cli(main)
```

**Comment by brentyi** [comment]
Agree that this would be good to support! Hopefully will be quick, since `List[T]` and `Dict[str, T]` already work.
