### ISSUE TITLE
Add an option to disallow abbreviations (argparse's `allow_abbrev = False`)

### ISSUE THREAD

**Issue by yohan-pg** [brentyi/tyro#45]
By default, argparse accepts any abbreviation for arguments (for example, `--pos` instead of `--position` will be accepted), but makes it possible to turn this off: https://docs.python.org/3/library/argparse.html#allow-abbrev.

Since admitting abbreviations like this can be error-prone, it would be nice to also have this option in tyro.

**Comment by brentyi** [comment]
Sorry for missing this earlier!

What do you think about just always passing in `allow_abbrev=False`? To be honest I wasn't even aware of this feature.

We could also add an argument, like `tyro.cli(main, allow_abbrev=False)`.

**Comment by yohan-pg** [comment]
I agree that the default should be false, I wasn't aware of this either until it lead to a really confusing bug.  I'm not sure if there is anyone that relies on this or not.

**Comment by brentyi** [comment]
Ok, I just set it in https://github.com/brentyi/tyro/commit/3de5c7f8220c0552db85a0fdd26faabe5f1ce31b. Will be available in the next release.

Thanks for raising this!

**Comment by yohan-pg** [comment]
Awesome :D 
Tyro is a great tool by the way, really nice work
