### ISSUE TITLE
How to specify an alias for a parameter

### ISSUE THREAD

**Issue by jhzgjhzg** [brentyi/tyro#54]
If a parameter name is too complex and I want to specify its abbreviation, how should I write it.
Similar to this:
`parser.add_argument("--target_img", "--ti", required=False, help="Path of reference image.")`
`--target_img` and `--ti`

**Comment by brentyi** [comment]
Hi!

Unfortunately we haven't added alias support. If this is something important to you I could add it to my to-do list; I'd expect it to be straightforward.

In the meantime, it _is_ possible to rename an argument:

```python
import dataclasses
from pathlib import Path

import tyro
from typing_extensions import Annotated


@dataclasses.dataclass
class Args:
    target_image: Annotated[Path, tyro.conf.arg(name="ti")]


# Takes --ti as an argument.
tyro.cli(Args)
```

**Comment by vwxyzjn** [comment]
👀 hi running into the same issue

**Comment by brentyi** [comment]
Ok, `0.5.12` should support aliases now. There's an example here: https://brentyi.github.io/tyro/examples/04_additional/11_aliases/

@jhzgjhzg for your example:
```python
target_img: Annotated[Optional[Path], tyro.conf.arg(aliases=["--ti"])] = None
```

@vwxyzjn for yours:

```python
temperature: Annotated[float, tyro.conf.arg(aliases=["-t])] = 1.0
max_new_tokens: Annotated[int, tyro.conf.arg(aliases=["-toks"]) = 1500
```
