### ISSUE TITLE
Pass in path to yaml config to specify params

### ISSUE THREAD

**Issue by breengles** [brentyi/tyro#55]
Hi! First of all, thank you for the wonderful cli tool!
Currently, I am playing around with it and wondering if there is any way to specify a path to the `.yaml` config file which contains (possibly, not with every params specified) to populate/edit the default config determined via dataclass? For example, in [`pyrallis`](https://github.com/eladrich/pyrallis) there is `--config_path`

**Comment by brentyi** [comment]
Hi!

We don't have Pyrallis-style YAML support unfortunately, although similar functionality should be very doable.

I think options are basically:

- Move away from YAML files entirely, a simple dictionary of configs is often enough: https://brentyi.github.io/tyro/examples/03_config_systems/01_base_configs/

- Implement the YAML loading logic manually. You could parse the `--config_path` argument before calling `tyro.cli()`, this is kind of what kaolin-wisp does ([docs](https://kaolin-wisp.readthedocs.io/en/latest/pages/config_system.html), [example code](https://github.com/NVIDIAGameWorks/kaolin-wisp/blob/main/wisp/config/_tyro.py)), and use it to manipulate the default passed to `tyro.cli()`. An environment variable also works. The exact details here depends on the specific YAML structure you want to use.
