### ISSUE TITLE
either `param_1`  or `param_2` as required on the same dataclass for different executes script

### ISSUE THREAD

**Issue by penguinflys** [brentyi/tyro#59]
Hallo, I have encounted a curcumastance like this:

```python
@dataclasses
class ModelConfig:
    source_path: Path
    """Source path where data included. if specified, model_path shall be assigned to a random path."""""
    model_path: Path
    """Path for the model, required for prediction."""
```
Then I use the following cmd:

`python train.py --model.source-path <xxx>` for training, and only `--model.source-path` is required for `training.py`, while model_path is not required.

`python inference.py --model.model-path <xxx>` for training, and only `--model.model-path` is required for `inference.py`, source_path can be left empty.

I am wondering How can set `source_path` required only to training.py, while `model_path` required only to inference.py

**Comment by brentyi** [comment]
Hi @penguinflys!

Here's a snippet that should run:
```python
# training.py

import functools
from dataclasses import dataclass
from pathlib import Path

import tyro


@dataclass
class ModelConfig:
    source_path: Path
    """Source path where data included. if specified, model_path shall be assigned to a random path.""" ""
    model_path: Path
    """Path for the model, required for prediction."""


tyro.cli(
    functools.partial(ModelConfig, model_path=Path("unused")),
)
```

Or, alternatively:
```python
# training.py

from dataclasses import dataclass
from pathlib import Path

import tyro


@dataclass
class ModelConfig:
    source_path: Path
    """Source path where data included. if specified, model_path shall be assigned to a random path.""" ""
    model_path: Path
    """Path for the model, required for prediction."""


tyro.cli(
    ModelConfig,
    default=ModelConfig(
        source_path=tyro.MISSING,
        model_path=Path("unused"),
    ),
)
```

Do either of these do what you want?

If there are unused arguments like this, I find that code can sometimes be refactored so that arguments only exist when they're actually used. For example, could `inference.py` be structured like:

```python
def main(model_path: Path, model_config: ModelConfig) -> None:
    ...

tyro.cli(main)
```

so that `model_path` doesn't need to exist in `ModelConfig`/`train.py` at all?

**Comment by penguinflys** [comment]
> Hi @penguinflys!
> 
> Here's a snippet that should run:
> 
> ```python
> # training.py
> 
> import functools
> from dataclasses import dataclass
> from pathlib import Path
> 
> import tyro
> 
> 
> @dataclass
> class ModelConfig:
>     source_path: Path
>     """Source path where data included. if specified, model_path shall be assigned to a random path.""" ""
>     model_path: Path
>     """Path for the model, required for prediction."""
> 
> 
> tyro.cli(
>     functools.partial(ModelConfig, model_path=Path("unused")),
> )
> ```
> 
> Or, alternatively:
> 
> ```python
> # training.py
> 
> from dataclasses import dataclass
> from pathlib import Path
> 
> import tyro
> 
> 
> @dataclass
> class ModelConfig:
>     source_path: Path
>     """Source path where data included. if specified, model_path shall be assigned to a random path.""" ""
>     model_path: Path
>     """Path for the model, required for prediction."""
> 
> 
> tyro.cli(
>     ModelConfig,
>     default=ModelConfig(
>         source_path=tyro.MISSING,
>         model_path=Path("unused"),
>     ),
> )
> ```
> 
> Do either of these do what you want?
> 
> If there are unused arguments like this, I find that code can sometimes be refactored so that arguments only exist when they're actually used. For example, could `inference.py` be structured like:
> 
> ```python
> def main(model_path: Path, model_config: ModelConfig) -> None:
>     ...
> 
> tyro.cli(main)
> ```
> 
> so that `model_path` doesn't need to exist in `ModelConfig`/`train.py` at all?

looks very neat, I will try it.

**Comment by penguinflys** [comment]
Have tried both solutions, both works great, thanks a lot for the careful written solutions!
