### ISSUE TITLE
How to get access to attribute doc string

### ISSUE THREAD

**Issue by vwxyzjn** [brentyi/tyro#74]
Hi @brentyi,

Thanks for this amazing repo. We are starting to use it at https://github.com/huggingface/trl. However, we ran into some auto docstring issues.

I have the following snippet.

```
@dataclass
class RewardConfig:
    """
    RewardConfig collects all training arguments related to the [`RewardTrainer`] class.

    Parameters:
        max_length (`int`, *optional*, defaults to `None`):
            The maximum length of the sequences in the batch. This argument is required if you want to use the default data collator.
        gradient_checkpointing (`bool`, *optional*, defaults to `True`):
                If True, use gradient checkpointing to save memory at the expense of slower backward pass.
    """

    max_length: Optional[int] = None
    """The maximum length of the sequences in the batch. This argument is required if you want to use the default data collator."""
    gradient_checkpointing: Optional[bool] = True
    """If True, use gradient checkpointing to save memory at the expense of slower backward pass."""
```

Do you know how I can programmatically generate the docs string for 

```
    Parameters:
        max_length (`int`, *optional*, defaults to `None`):
            The maximum length of the sequences in the batch. This argument is required if you want to use the default data collator.
        gradient_checkpointing (`bool`, *optional*, defaults to `True`):
                If True, use gradient checkpointing to save memory at the expense of slower backward pass.
```

using 

```
    max_length: Optional[int] = None
    """The maximum length of the sequences in the batch. This argument is required if you want to use the default data collator."""
    gradient_checkpointing: Optional[bool] = True
    """If True, use gradient checkpointing to save memory at the expense of slower backward pass."""
```

We use the docstring generate something like https://huggingface.co/docs/trl/v0.7.1/en/trainer#trl.PPOConfig

**Comment by brentyi** [comment]
Hi Costa! I'm glad the library's working for you!

I'm not 100% following your end goal here: is it to have each of these docstrings duplicated in your code? As in, the docstring for `max_length` appears once in the class docstring and once directly after the attribute definition? Or do you want to dynamically append the `Parameters:` docstring to the end of the class's `__doc__` field?

In either case it seems like you can read each attribute's docstring via something like docstring_parser, which [supports this style of docstrings](https://github.com/rr-/docstring_parser/issues/71). This is roughly what `tyro` does internally.

Alternatively, is it possible to add support for writing dataclasses with only attribute docstrings into Hugging Face's documentation generation tooling?

Sphinx and `pyright`, for example, directly understand:
```python
@dataclass
class RewardConfig:
    """
    RewardConfig collects all training arguments related to the [`RewardTrainer`] class.
    """

    max_length: Optional[int] = None
    """The maximum length of the sequences in the batch. This argument is required if you want to use the default data collator."""
    gradient_checkpointing: Optional[bool] = True
    """If True, use gradient checkpointing to save memory at the expense of slower backward pass."""
```
This feels much more efficient.

**Comment by vwxyzjn** [comment]
Watch you said exactly what I'm looking for. I have raised an issue in https://github.com/huggingface/doc-builder/issues/410
