### ISSUE TITLE
Help text output underscore instead of dashes

### ISSUE THREAD

**Issue by vwxyzjn** [brentyi/tyro#75]
Would it be possible to output underscore instead of dashes in the help text? E.g., ` --ddpo_config.exp_name` instead of ` --ddpo-config.exp-name`. I understand both options can be parsed but was just wondering if we could configure the help text to display underscore instead :) 

<img width="679" alt="image" src="https://github.com/brentyi/tyro/assets/5555347/d9312848-df73-47ca-9dc8-23a70c6dc4d3">

**Comment by brentyi** [comment]
Hi!

Swapping to underscores isn't currently supported, but it's been requested a few times and I'd be happy to add it.

This could be implemented as one of:
- `tyro.cli(tyro.conf.UseUnderscores[Args])` 
- `tyro.cli(Args, use_underscores=True)`
- `tyro.cli(Args, delimeter="underscore")`
- `tyro.cli(Args, delimeter="_")`

Thoughts? I could add it in the next few days (or would be happy to review a PR 🙂).

**Comment by vwxyzjn** [comment]
Hi @brentyi, I think `tyro.cli(Args, use_underscores=True)` would be great, probably implemented under the hood through `tyro.cli(Args, delimeter="_")`. I can't imagine any different delimiter use case, though... Something like `python test.py --myarg~subarg ` seems unlikely :)

**Comment by brentyi** [comment]
Added in `0.5.8`!
