### ISSUE TITLE
Arbitrary dict

### ISSUE THREAD

**Issue by vwxyzjn** [brentyi/tyro#79]
Can I have something like below?

```
@dataclass
class PPOConfig:
    tracker_kwargs: dict = field(default_factory=dict)
    """Keyword arguments for the tracker (e.g. wandb_project)"""
    accelerator_kwargs: dict = field(default_factory=dict)
    """Keyword arguments for the accelerator"""
    project_kwargs: dict = field(default_factory=dict)
```

If I try `python ppo.py --ppo_config.tracker_kwargs.entity=vwxyzjn` it gives me 

```
╭─ Parsing error ──────────────────────────────────────────────────────────────────────────────────╮
│ Argument [{peft-config:lora-config,peft-config:None}]: invalid choice:                           │
│ "--ppo-config.tracker-kwargs={'wandb': {'entity': wandb_entity, 'name': exp_name}}}" (choose     │
│ from 'peft-config:lora-config', 'peft-config:None')                                              │
│ ──────────────────────────────────────────────────────────────────────────────────────────────── │
│ For full helptext, run ppo.py --help  
```

Do I need to use `TypedDict`?

Related https://github.com/huggingface/trl/pull/897

**Comment by brentyi** [comment]
Yeah, dictionaries are generally tricky because we need to figure out the types of keys/values. `TypedDict` makes the parsing behavior less ambiguous; we currently support `total=` but not `NotRequired`.

Here's the current behavior for vanilla dictionaries:

**(1) Default dictionary provided.** ([relevant example](https://brentyi.github.io/tyro/examples/04_additional/02_dictionaries/))

If a default dictionary is provided, each field in the dictionary is expanded to its own argument. This is kind of similar to what happens when dataclasses are nested.

Example:
```python
from dataclasses import dataclass, field

import tyro


@dataclass
class PPOConfig:
    tracker_kwargs: dict = field(
        default_factory={
            "wandb": {
                "entity": "wandb_entity",
                "name": "exp_name",
            }
        }.copy
    )
    """Keyword arguments for the tracker (e.g. wandb_project)"""


tyro.cli(PPOConfig)
```
![image](https://github.com/brentyi/tyro/assets/6992947/beac27fd-c9eb-4381-ab1e-ea171b1d43c0)

This is what's happening in your example, but the default is an empty dictionary so no arguments are being created.

**(2) No default provided.**

If there's no default dictionary _and we have types for the keys and values of the dict_, then we create an argument in the form of `--tracker-kwargs [K V [K V ...]]`.

Example:

```python
from dataclasses import dataclass
from typing import Dict

import tyro


@dataclass
class PPOConfig:
    tracker_kwargs: Dict[str, str]
    """Keyword arguments for the tracker (e.g. wandb_project)"""


print(tyro.cli(PPOConfig))
```

![image](https://github.com/brentyi/tyro/assets/6992947/4f77360e-d0bd-49ff-b0e6-dd30d41121a9)

----

Does that make sense to you? I can think of some possibilities for improvement (like we could use behavior **(2)** instead of **(1)** when the default is an empty dictionary), but it seems hard to cover all of the possibilities of general dictionaries. Open to suggestions.

**Comment by vwxyzjn** [comment]
Thanks so much for the info! It does make sense. What if the dict looks like `{'wandb': {'entity': wandb_entity, 'name': exp_name}}`? Would it be possible to pass a json string directly?

**Comment by brentyi** [comment]
Not currently, but a dumb suggestion:

```python
from dataclasses import dataclass
import json
import tyro

@dataclass
class PPOConfig:
    tracker_kwargs_json: str

config = tyro.cli(PPOConfig)
tracker_kwargs = json.loads(config.tracker_kwargs_json)
```

It would be verbose, but there are some other projects that would benefit from an extra argument to [`tyro.conf.arg()`](https://brentyi.github.io/tyro/api/tyro/conf/#tyro.conf.arg) that lets you set a per-argument factory function. Would you use this?

```python
from dataclasses import dataclass
from typing import Annotated
import tyro

@dataclass
class PPOConfig:
    tracker_kwargs_json: Annotated[
        str,
        tyro.conf.arg(metavar="JSON", factory=json.loads),
    ]
```

**Comment by vwxyzjn** [comment]
The second solution looks like a viable option. Btw would `Dict[str, Dict[str, str]]` work somehow?

**Comment by brentyi** [comment]
Sure, I just made a PR and can try to get a release out in the next few days.

I think the example I put should also work with `Dict[str, Dict[str, str]]`:
```python
def dict_json_constructor(json: str) -> dict:
    """Construct a dictionary from a JSON string. Raises a ValueError if it fails."""
    out = json_.loads(json)
    if not isinstance(out, dict):
        raise ValueError(f"{json} is not a dictionary!")
    return out


# A dictionary type, but `tyro` will construct it with JSON.
JsonDict = Annotated[dict, tyro.conf.arg(constructor=dict_json_constructor)]


def main(
    dict1: JsonDict,
    dict2: JsonDict = {"default": None},
) -> None:
    print(dict1)
    print(dict2)
```

You would just replace `Annotated[dict, ...]` with `Annotated[Dict[str, Dict[str, str]], ...]` and add more thorough validation logic in the constructor function.

**Comment by brentyi** [comment]
Okay, I just did a `0.5.11` release which should support the pattern above.

If there any issues please let me know!

**Comment by vwxyzjn** [comment]
Can I do this:

```
from dataclasses import dataclass
from typing import Annotated, Optional
import tyro
import json

@dataclass
class PPOConfig:
    tracker_kwargs: Optional[Annotated[
        dict,
        tyro.conf.arg(metavar="JSON", constructor=json.loads),
    ]] = None

args = tyro.cli(PPOConfig)
print(args.tracker_kwargs)
```
```
python test4.py --tracker-kwargs='{"wandb":"haha"}'
╭─ Value error ────────────────────────────────────────────────────────────────────────────────────────╮
│ Error parsing --tracker-kwargs: no type in [<class 'NoneType'>, typing.Annotated] could be           │
│ instantiated from ['{"wandb":"haha"}'].                                                              │
│                                                                                                      │
│ Got errors:                                                                                          │
│ - <class 'NoneType'>: ['{"wandb":"haha"}'] does not match choices {'None'}                           │
│ - typing.Annotated: incomplete set of key value pairs!                                               │
│ ──────────────────────────────────────────────────────────────────────────────────────────────────── │
│ Argument helptext:                                                                                   │
│     --tracker-kwargs {None}|{[STR STR [STR STR ...]]}                                                │
│     (default: None)                                                                                  │
│ ──────────────────────────────────────────────────────────────────────────────────────────────────── │
│ For full helptext, see test4.py --help                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by vwxyzjn** [comment]
Nvm I figured it out, it should be

```
from dataclasses import dataclass
from typing import Annotated, Optional
import tyro
import json

@dataclass
class PPOConfig:
    tracker_kwargs: Annotated[
        Optional[dict],
        tyro.conf.arg(metavar="JSON", constructor=json.loads),
    ] = None

args = tyro.cli(PPOConfig)
print(args.tracker_kwargs)
```

**Comment by brentyi** [comment]
Glad you got it! Also will try to improve the error message in the first case at some point...
