### ISSUE TITLE
Tyro captures all ValueErrors

### ISSUE THREAD

**Issue by pyetras** [brentyi/tyro#86]
Whenever the function called by tyro.cli raises a ValueError, it's being captured by tyro, assumed to be an argument parsing error and reformatted. The reformatting makes it difficult to understand the issue, as it hides the stack trace. I could not find a way to switch off this behaviour.

<img width="599" alt="image" src="https://github.com/brentyi/tyro/assets/54767/3d67c7aa-7af2-4397-a2f0-58bbeb5d629b">

**Comment by brentyi** [comment]
Thanks! I just pushed a fix + release. Let me know if it's still not working!

**Comment by kevinddchen** [comment]
Can confirm that `0.5.14` fixed the issue on my end.

**Comment by pyetras** [comment]
Thank you! That was blazing fast
