### ISSUE TITLE
Does the recent feature for typing_extensions.NotRequired support the functional syntax?

### ISSUE THREAD

**Issue by saeejithnair** [brentyi/tyro#87]
Thanks for adding this feature! Is the parsing supposed to work with the [functional syntax](https://peps.python.org/pep-0589/#alternative-syntax) or does it only support the class-based syntax rn?

E.g. I just tried the following on `v0.5.14` and neither of the two examples below seem to work and it shows up as **required** in the help text... Is there something wrong with my syntax? I'm on `python3.9` so I'm importing these via `typing_extensions` instead of `Typing` [as suggested here](https://peps.python.org/pep-0655/#usage-in-python-3-11).

```
from typing_extensions import TypedDict, NotRequired
from typing import Callable, Literal, Optional, Type, Dict, Union

NerfMLPHiddenLayers_1 = TypedDict(
    "NerfMLPHiddenLayers1",
    {
        "hidden_layers.0": NotRequired[int],
        "hidden_layers.1": NotRequired[int],
        "hidden_layers.2": NotRequired[int],
        "hidden_layers.3": NotRequired[int],
        "hidden_layers.4": NotRequired[int],
        "hidden_layers.5": NotRequired[int],
        "hidden_layers.6": NotRequired[int],
        "hidden_layers.7": NotRequired[int],
    },
)

NerfMLPHiddenLayers_2 = TypedDict(
    "NerfMLPHiddenLayers2",
    {
        "hidden_layers.0": int,
        "hidden_layers.1": int,
        "hidden_layers.2": int,
        "hidden_layers.3": int,
        "hidden_layers.4": int,
        "hidden_layers.5": int,
        "hidden_layers.6": int,
        "hidden_layers.7": int,
    },
    total=False
)
```

<img width="498" alt="image" src="https://github.com/brentyi/tyro/assets/16181437/e83a6dc2-f3b7-4db6-863c-c26c517867e7">

**Comment by brentyi** [comment]
Hi @saeejithnair, thanks for flagging this!

This looks like it's probably a bug, but I haven't been able to reproduce it. I just pushed a test that also checks this behavior in the CI. Do you mind sharing a runnable example, or perhaps more information about your Python environment? (like the `typing_extensions` version)

**Comment by brentyi** [comment]
Actually, I think I figured it out — there was an edge case when a TypedDict field had a default specified, which is probably the case in your NeRF config. I just did a release that should have the issue fixed. (if it's not would appreciate you letting me know!)
