### ISSUE TITLE
Configure width or avoid truncation on long names in helptext

### ISSUE THREAD

**Issue by wookayin** [brentyi/tyro#91]
```
╭─ arguments ─────────────────────────────────────────────────────────────╮
│ -h, --help        show this help message and exit                       │
╰─────────────────────────────────────────────────────────────────────────╯
╭─ subcommands ───────────────────────────────────────────────────────────╮
│ {foo,generate_completion}                                               │
│     foo               Foo bar                                           │
│     generate_completi…Generate *zsh* tab completion file.               │
╰─────────────────────────────────────────────────────────────────────────╯
```

The subcommand `    generate_completion` is too long, truncated at 24 characters. How can I configure this so that no truncation would happen?

This value 24 is hard-coded at: https://github.com/brentyi/tyro/blob/v0.5.18/tyro/_argparse_formatter.py#L841

It would have been much better if this were a static field/member rather than a local variable. Ideally, we should have an API to configure the behavior on `help_position` or the width.

The version I used:
- tyro 0.5.17
- CPython 3.11.6

**Comment by brentyi** [comment]
Thanks for flagging!

This looks like a bug; I would've expected the description text to wrap to the next line. It appears it does when I just make your subcommand a little bit longer:
![image](https://github.com/brentyi/tyro/assets/6992947/181b332d-58b9-4900-8970-7aa850caabfe)

I can look into this in the next few days.

**Comment by wookayin** [comment]
Thanks for the fix. How about also making the constants `max_help_position = 24`, etc. as a static field of the class?

**Comment by brentyi** [comment]
Currently none of this is exposed in the public API. Are you proposing to add an argument to `tyro.cli()`?

**Comment by wookayin** [comment]
We probably don't want to soil the arguments of `tyro.cli`. 

I was thinking of more like:
```diff
 class TyroArgparseHelpFormatter(argparse.RawDescriptionHelpFormatter):
+   indent_increment = 4
+   max_help_position = 24

     def __init__(self, prog: str):
-        indent_increment = 4
         width = shutil.get_terminal_size().columns - 2
-        max_help_position = 24
```
so that one can do monkey-patching of those values at users' own risk (although it's not a public API yet). But given that the truncation no longer happens, I'm fine with not having this too.

**Comment by brentyi** [comment]
Got it, ok!

Since you don't feel strongly I'll just hold off, if we want more configuration of how the helptext is displayed I'd prefer to make more intentional decisions on that. Ideally we could revisit it jointly with things like the design of [tyro.extras.set_accent_color()](https://brentyi.github.io/tyro/api/tyro/extras/#tyro.extras.set_accent_color). But it's challenging to prioritize...
