### ISSUE TITLE
Bug for `__post_init__` logic

### ISSUE THREAD

**Issue by Reza-esfandiarpoor** [brentyi/tyro#97]
## Problem description

When nesting dataclasses, if there is a default value for inner dataclasses that impacts the logic in their `__post_init__` method, the new values from command line do not impact the logic in `__post_init__ `.

## Code to reproduce:

```python
@dataclass
class ArgumentsOne:
    num_gpus: int
    num_cpus: Optional[int] = None

    def __post_init__(self):
        if self.num_cpus is None:
            self.num_cpus = 2 * self.num_gpus


@dataclass
class ScriptArguments:
    dataset: str = "X"
    one: ArgumentsOne = field(default_factory=lambda: ArgumentsOne(num_gpus=1))


print(tyro.cli(ScriptArguments))
```

Command: `python main.py --one.num_gpus=2`

tyro version: tyro==0.5.18

### Current output:

```
ScriptArguments(dataset='X', one=ArgumentsOne(num_gpus=2, num_cpus=2))
```

### Expected output:

```
ScriptArguments(dataset='X', one=ArgumentsOne(num_gpus=2, num_cpus=4))
```

## Related problem

There is also a similar situation for sanity checks. For example, if `ArgumentsOne` checks to make sure we have GPUs when asking for them with an statement like the following in the `__post_init__`, we will face a similar problem.

```python
...
class ArgumentsOne:
    ...
    def __post_init__(self):
        ...
        if self.num_gpus > 0:
            # raise value error if we do not have access to gpus
```

In this case, if the original script is configured to run on a machine with GPUs by default but we want to run it on a machine without GPUs with `--one.num_gpus=0`, we will get a value error.

## Example use cases

Huggingface transformers adds a significant amount of logic to its TrainerConfig `__post_init__` method, for example [here](https://github.com/huggingface/transformers/blob/514de24abfd4416aeba6a6455ad5920f57f3567d/src/transformers/training_args.py#L161).

This is used in this [example script](https://github.com/huggingface/trl/blob/55d7c952c796345d9fa520e692f7760372b14b43/examples/research_projects/stack_llama_2/scripts/sft_llama2.py#L32). For the reasons explained above, you cannot use this script as is on older GPUs even if you do `--training-args.bf16=False` and you will get an error saying that your machine does not have the ability to use bf16 data type.

**Comment by brentyi** [comment]
Hi!

To clarify your first example, if you wrote it (equivalently) as:
```python
@dataclass
class ScriptArguments:
    dataset: str = "X"
    one: ArgumentsOne = field(default_factory=lambda: ArgumentsOne(
        num_gpus=1,
        num_cpus=2,
    ))
```

would you expect `--one.num-cpus` to default to `None`, or default to `2`?  Your problem seems to be because `tyro` chooses the latter behavior.

In your latter problem, I speculate that the problem with this is:
```python
class ArgumentsOne:
    ...
    def __post_init__(self):
        ...
        if self.num_gpus > 0:
            # raise value error if we do not have access to gpus
```
when you've written:
```python
    one: ArgumentsOne = field(default_factory=lambda: ArgumentsOne(num_gpus=1))
```
`tyro` needs to run the default_factory in order to inspect what you want the default value to be (and then allow it to be overridden). This will instantiate an `ArgumentsOne` object with `num_gpus=1`, which will throw an error. Is that incorrect behavior?

**Comment by Reza-esfandiarpoor** [comment]
Thank you for your quick response!

To avoid confusion, let me first explain the ideal outcome in my use case and answer your questions at the end.
I think there are two approaches or design choices for dealing with the default values.

The first approach is to first create a default object and then override the values one by one. I am not familiar with the inner workings of `tyro`, but it seems like this is what `tyro` is doing currently. This will look something like this:

```python
# python  main.py --one.num_gpus=0

object = ScriptArguments(one=ArgumentsOne(num_gpus=1))
object.one.num_gpus = 0
# We continue doing this for all key values mentioned in the command line.
return object
```
The downside with this approach is that we are unable to influence the logic in the `__post_init__` from the command line and it is always executed with default values. So, the logic in `__post_init__ ` always assumes that we are requesting one GPU (i.e., `num_gpus=1`) and throws an error if our machine does not have GPUs even if we specify on the command line that we do not need GPUs with `--one.num_gpus=0`.


The alternative approach is to merge the values from the command line with the default values and instantiate a new object. Basically, to determine the key values passed as arguments to the constructor of the dataclasses, use the key values passed on the command line. But, if a key value is in the hard-coded default in the script but not on the command line, use the hard-coded default value. This will look something like this:

```python
# python main.py --one.num_gpus=0
object = ScriptArguments(one=ArgumentsOne(num_gpus=0))

# python main.py --dataset=mnist --one.num_gpus=0
object = ScriptArguments(dataset='mnist', one=ArgumentsOne(num_gpus=0))

# python main.py --dataset=mnist --one.num_cpus=2
object = ScriptArguments(dataset='mnist', one=ArgumentsOne(num_gpus=1, num_cpus=2))

# python main.py --dataset=mnist
object = ScriptArguments(dataset='mnist', one=ArgumentsOne(num_gpus=1))
```

Following this approach, we can change the behavior of the `__post_init__` from the command line. For example, if we specify on the command line that we do not want GPUs (`--one.num_gpus=0`), then the `__post_init__ ` logic is not gonna check if the machine has GPUs and will not throw an error, which makes the script more portable.


Another example of `__post_init__` logic is derived values. In a simple case, if the value of field `num_cpus` is derived from the value of `num_gpus` by some logic, then regardless of what we choose for `num_gpus` from the command line, `num_cpus` is gonna get the same value since `__post_init__ ` logic uses  the default value of `num_gpus` to calculate `num_cpus`. The only option is to also override `num_cpus` from the command line as well, which in this simple case is feasible. But, for more complex libraries like huggingface, there are many many variables to override on the command line and the logic is sometimes too complex to apply manually.


To answer your questions:

> would you expect --one.num-cpus to default to None, or default to 2? Your problem seems to be because tyro chooses the latter behavior.

We want it to default to 2 because in the code sample you provided it is specifically mentioned that `num_cpus` should be 2 when instantiating the new object. And if we follow the second design approach, which is the desired behavior in this case, then since we have not specified a value for `num_cpus` on the command line, it should use the default value of 2.

> ... which will throw an error. Is that incorrect behavior?

I would say it is not the expected behavior for this specific application and in general for situations where the `__post_init__` implements a significant amount of logic.

- If the developers decide not to cover these more complex cases like in huggingface, then `tyro` is doing what it is expected to and this is not incorrect but that `tyro` is not the suitable tool to use in this case.
- But if the intention is to be able to use `tyro` in this case, then, the behavior is incorrect and the class should not be instantiated with `num_gpus=1` when we specify on the command line `--one.num_gpus=0`.



I would also like to briefly discuss the strength of `tyro` in my workflow specifically with huggingface in case it is helpful since `tyro` is still under active development.
One of the amazing things that huggingface does in libraries like `transformers` and `trl` is that it provides a huge number of options that cover most use cases. But `HfArgumentParser` is not compatible with nested structures. So you have to either watch out for all the possible name collisions that occur now or in the future between different configuration objects or alternatively, define a set of command line arguments that you want to use and then initialize the configuration objects manually with command line values. The latter is what most scripts do which makes for lengthy scripts like [this one](https://github.com/artidoro/qlora/blob/7f4e95a68dc076bea9b3a413d2b512eca6d004e5/qlora.py#L79-L246). or this one ([Here](https://github.com/huggingface/trl/blob/55d7c952c796345d9fa520e692f7760372b14b43/examples/scripts/sft.py#L32-L75) and [Here](https://github.com/huggingface/trl/blob/55d7c952c796345d9fa520e692f7760372b14b43/examples/scripts/sft.py#L113-L129) in the code)

`tyro` is quite useful here because it supports nesting so no worries about name conflicts and unlike the second example, we do not have to update the script every time we want to use a new flag for huggingface Trainer that we have not used before.

**Comment by Reza-esfandiarpoor** [comment]
Thank you! It makes perfect sense. I think then there is nothing that can be done for when the default initialization throws an error because it has to be run with the default values to generate helptext, etc. before the user even enters custom values through the command line. But I think the end user can work around it by choosing more general defaults that are more portable.

As for the problem of derived values, it seems like the issue arises only when part of the `__post_init__` logic is executed in certain situations like when some field like `num_cpus` is None. And now the second time that `tyro` calls the `__post_init__` function after overriding the values, then the logic is ignored since the field (`num_cpus` in this case) already has a value as a result of the first `__post_init__` call and is not None anymore.

I think my proposed approach is not applicable currently because `tyro` has no way of knowing how `default_factory` creates the instance so it cannot update the constructor arguments and instantiate a new object, it can only call `default_factory` which always initializes the object the same way with default values.

Maybe in the future, there can be an extra utility that takes a callable and default arguments to create the instance. For example something like `tyro.custom_factory(init_fn, init_args={key: value})` and then to create the final object, it can combine the command line values with default values (e.g., `custom_args = init_args + {values specified on the command line}`) and call the given init function with these values to get the final object, something like `init_fn(**custom_args)`.
