### ISSUE TITLE
Conditional presets?

### ISSUE THREAD

**Issue by vwxyzjn** [brentyi/tyro#98]
Not sure how to put this in words but I want this:

```
@dataclass
class Args:
    base_model: str = "gpt2" # EleutherAI/pythia-160m
    max_sft_response_length: int = 48 # 53
    max_rm_response_length: int = 153 # 169
```

When specifying `python test.py --base_model=gpt2` the `max_sft_response_length=48` and `max_rm_response_length=153`, but when doing `python test.py --base_model=EleutherAI/pythia-160m` the `max_sft_response_length=53
` and `max_rm_response_length=169`.

Basically I want the `max_sft_response_length` `max_rm_response_length` to be dependent on `base_model`. Any idea how to achieve this?

**Comment by brentyi** [comment]
Would it make sense to move these to a method or property?

Like:
```python
@dataclass
class Args:
    base_model: str = "gpt2" # EleutherAI/pythia-160m

    def get_max_sft_response_length(self) -> int:
        if self.base_model == "gpt2":
            return 48
        elif self.base_model == "EleutherAI/pythia-160m":
            return 53
        else:
            assert False, f"{self.base_model} was not found!"
```

or:

```python
@dataclass
class Args:
    base_model: str = "gpt2" # EleutherAI/pythia-160m

    @property
    def max_sft_response_length(self) -> int:
        if self.base_model == "gpt2":
            return 48
        elif self.base_model == "EleutherAI/pythia-160m":
            return 53
        else:
            assert False, f"{self.base_model} was not found!"
```

People sometimes also like to add this kind of logic to the dataclass's `__post_init__()`, but I think the method/property pattern is cleaner because it reduces mutation. (and can reduce the likelihood of confusing behavior like in #97)

**Comment by vwxyzjn** [comment]
makes sense thanks!
